In [2]:
import pandas as pd

In [3]:
raw_path = '/Users/vladislav/Documents/vlzm/GFDRR/data/raw/202601-citibike-tripdata_1.csv'
data = pd.read_csv(raw_path)
data.head()

/var/folders/bc/6rm76y3s2f7180l31j70ss7h0000gn/T/ipykernel_65158/703940717.py:2: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(raw_path)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,85744AF35D7F2DF5,electric_bike,2026-01-02 05:36:24.539,2026-01-02 05:42:21.153,W 42 St & 8 Ave,6602.05,E 58 St & Madison Ave,6839.04,40.757570,-73.990985,40.763026,-73.972095,member
1,9D18958E5788880B,electric_bike,2026-01-02 15:15:11.915,2026-01-02 15:18:40.462,Division St & Bowery,5311.08,Clinton St & Grand St,5303.06_,40.714190,-73.996730,40.715738,-73.986990,member
2,B050891B7B009EE5,electric_bike,2026-01-12 10:12:51.453,2026-01-12 10:16:55.731,Broadway & 31 St,6789.08,35 Ave & 37 St,6563.12,40.761940,-73.925130,40.755733,-73.923661,member
3,0B6D7938C4EF1668,electric_bike,2026-01-01 01:03:29.712,2026-01-01 01:05:37.341,34 St & 35 Ave,6605.08,35 St & Broadway,6750.16,40.756933,-73.926223,40.760339,-73.922243,member
4,95415F60C7120CC3,electric_bike,2026-01-03 19:55:51.636,2026-01-03 20:14:57.964,E 6 St & Ave B,5584.04,W 55 St & 6 Ave,6809.09,40.724537,-73.981854,40.763189,-73.978434,member

In [6]:
raw_path = '/Users/vladislav/Documents/vlzm/GFDRR/data/raw/JC-202601-citibike-tripdata.csv'
data = pd.read_csv(raw_path)
data.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,40FBC7AEEBB220EC,electric_bike,2026-01-11 15:01:01.954,2026-01-11 15:16:57.103,14 St Ferry - 14 St & Shipyard Ln,HB202,Pier 61 at Chelsea Piers,6233.04,40.752961,-74.024353,40.746872,-74.00821,member
1,47FB1CA65D3F7E0F,electric_bike,2026-01-16 11:49:41.364,2026-01-16 11:58:27.291,14 St Ferry - 14 St & Shipyard Ln,HB202,Madison St & 1 St,HB402,40.752961,-74.024353,40.738790,-74.03930,member
2,BFB10DE1E40F3709,electric_bike,2026-01-07 19:55:41.424,2026-01-07 19:59:09.874,Church Sq Park - 5 St & Park Ave,HB601,Madison St & 1 St,HB402,40.742659,-74.032233,40.738790,-74.03930,member
3,F16B896495AAF618,electric_bike,2026-01-24 11:12:10.547,2026-01-24 11:34:42.801,Madison St & 1 St,HB402,Madison St & 1 St,HB402,40.738790,-74.039300,40.738790,-74.03930,member
4,76D77D5F1D491B3C,electric_bike,2026-01-22 20:58:00.602,2026-01-22 21:02:39.088,Clinton St & 7 St,HB303,Madison St & 1 St,HB402,40.745420,-74.033320,40.738790,-74.03930,casual

In [4]:
raw_path = '/Users/vladislav/Documents/vlzm/GFDRR/data/raw/202601-citibike-tripdata_2.csv'
data = pd.read_csv(raw_path)
data.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0179695DC1F74E4E,classic_bike,2026-01-09 15:39:44.131,2026-01-09 15:44:27.970,Adam Clayton Powell Blvd & W 115 St,7643.18,St Nicholas Ave & Manhattan Ave,7723.01,40.802535,-73.953242,40.809725,-73.953149,member
1,5D0645202DDFA256,electric_bike,2026-01-09 10:14:39.226,2026-01-09 10:18:56.254,Carlton Ave & Dean St,4199.12,3 Ave & Schermerhorn St,4437.01,40.680974,-73.971010,40.686832,-73.979677,member
2,4572C883BF0165E4,classic_bike,2026-01-14 18:44:00.839,2026-01-14 18:52:54.180,Broadway & Morris St,5033.01,Lispenard St & Broadway,5391.06,40.705945,-74.013219,40.719392,-74.002472,member
3,3575D616D0179F57,electric_bike,2026-01-06 05:57:18.257,2026-01-06 06:15:40.651,Van Brunt St & Wolcott St,4095.03,Vesey St & Church St,5216.06,40.677343,-74.012751,40.712220,-74.010472,member
4,895D2DC8F8BA4177,electric_bike,2026-01-02 16:19:07.373,2026-01-02 16:24:19.447,W 33 St & 10 Ave,6492.04,6 Ave & W 33 St,6364.07,40.753773,-73.999376,40.749013,-73.988484,member

In [7]:
import requests
import pandas as pd

DISCOVERY_URL = "https://gbfs.citibikenyc.com/gbfs/2.3/gbfs.json"
LANG = "en"

def get_json(url: str, timeout: int = 15) -> dict:
    r = requests.get(url, timeout=timeout)
    r.raise_for_status()
    return r.json()

# 1) discovery: получаем реальные URL фидов
discovery = get_json(DISCOVERY_URL)
feeds = {f["name"]: f["url"] for f in discovery["data"][LANG]["feeds"]}

# 2) базовые фиды: география/метаданные станций + текущий статус
station_info = get_json(feeds["station_information"])["data"]["stations"]
station_status = get_json(feeds["station_status"])["data"]["stations"]

df_info = pd.DataFrame(station_info)
df_status = pd.DataFrame(station_status)

# 3) join по station_id
df = df_info.merge(df_status, on="station_id", how="left", suffixes=("_info", "_status"))

# пример: топ-15 станций по доступным велосипедам прямо сейчас
cols = ["station_id", "name", "lat", "lon", "num_bikes_available", "num_docks_available", "is_installed", "is_renting", "is_returning", "last_reported"]
print(df[cols].sort_values("num_bikes_available", ascending=False).head(15))

                                station_id                     name  \
442   66de25bd-0aca-11e7-82f6-3863bb44ef7c             3 St & 3 Ave
679   66ddbd20-0aca-11e7-82f6-3863bb44ef7c          8 Ave & W 31 St
1718  ff2869f0-4381-4cf3-863e-a0d776ec53b4      Old Slip & South St
1827  66db6387-0aca-11e7-82f6-3863bb44ef7c       Broadway & E 14 St
625   66ddea2a-0aca-11e7-82f6-3863bb44ef7c          E 91 St & 2 Ave
1525  66dbe4db-0aca-11e7-82f6-3863bb44ef7c          W 31 St & 7 Ave
919   66dc24b8-0aca-11e7-82f6-3863bb44ef7c         W 20 St & 11 Ave
1321  66dbe848-0aca-11e7-82f6-3863bb44ef7c     Centre St & Worth St
867   bde94a25-6089-4490-af3a-8cc5702230b8   W Broadway & Spring St
594   66dc3f08-0aca-11e7-82f6-3863bb44ef7c          W 41 St & 8 Ave
1021  e8df73bd-5d3d-47c9-b04d-bcec4db5540f     Cliff St & Fulton St
561   66db4282-0aca-11e7-82f6-3863bb44ef7c          W 11 St & 6 Ave
1874                   1963272613486484230          E 15 St & 5 Ave
1680  66dbc982-0aca-11e7-82f6-3863bb44ef7c       E 47 St & Park Ave
757   66db89a3-0aca-11e7-82f6-3863bb44ef7c  DeKalb Ave & Hudson Ave

            lat        lon  num_bikes_available  num_docks_available  \
442   40.675070 -73.987752                   72                    3
679   40.750585 -73.994685                   72                    6
1718  40.703367 -74.007868                   71                   17
1827  40.734546 -73.990741                   70                   23
625   40.781153 -73.949630                   65                    4
1525  40.749156 -73.991600                   63                   13
919   40.746745 -74.007756                   61                    0
1321  40.714948 -74.002345                   57                   36
867   40.724947 -74.001659                   55                    5
594   40.756405 -73.990026                   55                   20
1021  40.708380 -74.004950                   55                    3
561   40.735324 -73.998004                   53                    2
1874  40.736592 -73.992949                   53                    8
1680  40.755103 -73.974987                   53                   45
757   40.689888 -73.981013                   53                    6

      is_installed  is_renting  is_returning  last_reported
442              1           1             1     1770479723
679              1           1             1     1770479753
1718             1           1             1     1770479698
1827             1           1             1     1770479752
625              1           1             1     1770479739
1525             1           1             1     1770479714
919              1           1             1     1770479723
1321             1           1             1     1770479736
867              1           1             1     1770479747
594              1           1             1     1770479725
1021             1           1             1     1770479714
561              1           1             1     1770479716
1874             1           1             1     1770479701
1680             1           1             1     1770479722
757              1           1             1     1770479658

In [15]:
df_info

,station_id,name,region_id,rental_uris,capacity,lat,short_name,lon
0,1905837242740508940,31 St & Broadway,71,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,35,40.762110,6789.20,-73.925230
1,41495491-5d89-4e14-aab9-c3db04aad399,43 St & Skillman Ave,71,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,19,40.746927,6325.01,-73.920825
2,b9720921-8170-43ea-a5ae-b61b9161eb49,5 Ave & E 87 St,71,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,39,40.782323,7323.09,-73.959875
3,2171903608969565866,Jerome Ave & E Mosholu Pkwy N,71,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,0,40.880310,8824.02,-73.884260
4,2171904223419888148,E Gun Hill Rd & Tryon Ave,71,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,0,40.880200,8821.07,-73.876970
...,...,...,...,...,...,...,...,...
2350,b6a13f2b-deb4-4f4d-9d67-7d23bee27c88,2 St & Park Ave,311,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,15,40.739153,HB608,-74.033082
2351,46813ecf-8df4-4c8f-9579-0179e0b36ba6,Marshall St & 2 St,311,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,18,40.740802,HB408,-74.042521
2352,2108373961268485100,Arlington Ave & Wilkinson Ave,70,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,14,40.704503,JC127,-74.077210
2353,66dddc08-0aca-11e7-82f6-3863bb44ef7c,Columbus Drive,70,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,14,40.718355,JC014,-74.038914
2354,cbc48689-7805-49dd-9669-5471f4b7b6fb,Hoboken Terminal - Hudson St & Hudson Pl,311,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,24,40.735938,HB101,-74.030305

In [13]:
df_status

,station_id,last_reported,vehicle_types_available,num_docks_disabled,num_bikes_disabled,num_docks_available,is_installed,num_bikes_available,is_renting,num_ebikes_available,is_returning,num_scooters_unavailable,num_scooters_available
0,1905837242740508940,86400,"[{'vehicle_type_id': '1', 'count': 0}, {'vehic...",0,0,0,0,0,0,0,0,NaN,NaN
1,41495491-5d89-4e14-aab9-c3db04aad399,86400,"[{'vehicle_type_id': '1', 'count': 0}, {'vehic...",0,0,0,0,0,0,0,0,NaN,NaN
2,b9720921-8170-43ea-a5ae-b61b9161eb49,86400,"[{'vehicle_type_id': '1', 'count': 0}, {'vehic...",0,0,0,0,0,0,0,0,NaN,NaN
3,2171903608969565866,86400,"[{'vehicle_type_id': '1', 'count': 0}, {'vehic...",0,0,0,0,0,0,0,0,NaN,NaN
4,2171904223419888148,86400,"[{'vehicle_type_id': '1', 'count': 0}, {'vehic...",0,0,0,0,0,0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2350,2108372903577159978,1770479737,"[{'vehicle_type_id': '1', 'count': 3}, {'vehic...",0,0,10,1,5,1,2,1,0.0,0.0
2351,2088688422524183306,1770479747,"[{'vehicle_type_id': '1', 'count': 5}, {'vehic...",0,8,16,1,13,1,8,1,0.0,0.0
2352,581211b2-4e42-48f2-8a8f-5f968cb1c5df,1770419451,"[{'vehicle_type_id': '1', 'count': 0}, {'vehic...",0,17,15,1,0,0,0,0,0.0,0.0
2353,46813ecf-8df4-4c8f-9579-0179e0b36ba6,1770479752,"[{'vehicle_type_id': '1', 'count': 3}, {'vehic...",0,1,11,1,6,1,3,1,0.0,0.0
2354,9d344652-976b-4c2d-bede-2ef19b0fbf13,1770479755,"[{'vehicle_type_id': '1', 'count': 5}, {'vehic...",0,1,5,1,12,1,7,1,0.0,0.0

In [ ]:
тоесть у меня есть

station_id
capacity
lat
lon
num_bikes_available